version: 2

jobs:
  lint:
    docker:
    - image: "python:3.5-stretch"
    steps:
    - checkout
    - run: python3 -m pip install flake8
    - run: flake8 inference_server.py


workflows:
  version: 2
  lint:
    jobs:
      - lint
